# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Gallery
version:      0.7
version_from: lib/Apache/Gallery.pm
installdirs:  site
requires:
    CGI:                           2.93
    CGI::FastTemplate:             0
    File::Spec:                    0
    Image::Imlib2:                 1
    Image::Info:                   0
    Image::Size:                   0
    mod_perl:                      0
    Test::More:                    0
    URI:                           1.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
